production:
  secret_token: "my_secret_token"
  secret_key_base: ENV["SECRET_KEY_BASE"]

development:
  secret_token: "my_secret_token"
  secret_key_base: ENV["SECRET_KEY_BASE"]

test:
  secret_token: "my_secret_token"
  secret_key_base: ENV["SECRET_KEY_BASE"]
